// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uckhoeyhdcqxmceyvsza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVja2hvZXloZGNxeG1jZXl2c3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1MjIwOTEsImV4cCI6MjA3NTA5ODA5MX0.qaj08QyLMXwTbtUbpv1Xgsllg8XivKUSD4o0JPa0-t8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);